// automatically generated by the FlatBuffers compiler, do not modify

package fast_.Element_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous0 extends Table {
  public static Anonymous0 getRootAsAnonymous0(ByteBuffer _bb) { return getRootAsAnonymous0(_bb, new Anonymous0()); }
  public static Anonymous0 getRootAsAnonymous0(ByteBuffer _bb, Anonymous0 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous0 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int srcmlKind() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int smaliKind() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int python3Kind() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int solidityKind() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createAnonymous0(FlatBufferBuilder builder,
      int srcml_kind,
      int smali_kind,
      int python3_kind,
      int solidity_kind) {
    builder.startObject(4);
    Anonymous0.addSolidityKind(builder, solidity_kind);
    Anonymous0.addPython3Kind(builder, python3_kind);
    Anonymous0.addSmaliKind(builder, smali_kind);
    Anonymous0.addSrcmlKind(builder, srcml_kind);
    return Anonymous0.endAnonymous0(builder);
  }

  public static void startAnonymous0(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSrcmlKind(FlatBufferBuilder builder, int srcmlKind) { builder.addInt(0, srcmlKind, 0); }
  public static void addSmaliKind(FlatBufferBuilder builder, int smaliKind) { builder.addInt(1, smaliKind, 0); }
  public static void addPython3Kind(FlatBufferBuilder builder, int python3Kind) { builder.addInt(2, python3Kind, 0); }
  public static void addSolidityKind(FlatBufferBuilder builder, int solidityKind) { builder.addInt(3, solidityKind, 0); }
  public static int endAnonymous0(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

