// automatically generated by the FlatBuffers compiler, do not modify

package fast_.Graph_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Edge extends Table {
  public static Edge getRootAsEdge(ByteBuffer _bb) { return getRootAsEdge(_bb, new Edge()); }
  public static Edge getRootAsEdge(ByteBuffer _bb, Edge obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Edge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int node1() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int node2() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createEdge(FlatBufferBuilder builder,
      int node1,
      int node2) {
    builder.startObject(2);
    Edge.addNode2(builder, node2);
    Edge.addNode1(builder, node1);
    return Edge.endEdge(builder);
  }

  public static void startEdge(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addNode1(FlatBufferBuilder builder, int node1) { builder.addInt(0, node1, 0); }
  public static void addNode2(FlatBufferBuilder builder, int node2) { builder.addInt(1, node2, 0); }
  public static int endEdge(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

