// automatically generated by the FlatBuffers compiler, do not modify

package fast_.Graph_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NodeLabel extends Table {
  public static NodeLabel getRootAsNodeLabel(ByteBuffer _bb) { return getRootAsNodeLabel(_bb, new NodeLabel()); }
  public static NodeLabel getRootAsNodeLabel(ByteBuffer _bb, NodeLabel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public NodeLabel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int node() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String label() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer labelAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer labelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createNodeLabel(FlatBufferBuilder builder,
      int node,
      int labelOffset) {
    builder.startObject(2);
    NodeLabel.addLabel(builder, labelOffset);
    NodeLabel.addNode(builder, node);
    return NodeLabel.endNodeLabel(builder);
  }

  public static void startNodeLabel(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addNode(FlatBufferBuilder builder, int node) { builder.addInt(0, node, 0); }
  public static void addLabel(FlatBufferBuilder builder, int labelOffset) { builder.addOffset(1, labelOffset, 0); }
  public static int endNodeLabel(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

