// automatically generated by the FlatBuffers compiler, do not modify

package fast_.Slices_.Slice_.SourceFile_.Function_.Variable_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Position extends Table {
  public static Position getRootAsPosition(ByteBuffer _bb) { return getRootAsPosition(_bb, new Position()); }
  public static Position getRootAsPosition(ByteBuffer _bb, Position obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String location() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer locationAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer locationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String deltaLocation() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deltaLocationAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer deltaLocationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createPosition(FlatBufferBuilder builder,
      int locationOffset,
      int type,
      int delta_locationOffset) {
    builder.startObject(3);
    Position.addDeltaLocation(builder, delta_locationOffset);
    Position.addType(builder, type);
    Position.addLocation(builder, locationOffset);
    return Position.endPosition(builder);
  }

  public static void startPosition(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addOffset(0, locationOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(1, type, 0); }
  public static void addDeltaLocation(FlatBufferBuilder builder, int deltaLocationOffset) { builder.addOffset(2, deltaLocationOffset, 0); }
  public static int endPosition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

