// automatically generated by the FlatBuffers compiler, do not modify

package fast_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Graph extends Table {
  public static Graph getRootAsGraph(ByteBuffer _bb) { return getRootAsGraph(_bb, new Graph()); }
  public static Graph getRootAsGraph(ByteBuffer _bb, Graph obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Graph __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fast_.Graph_.Unit unit(int j) { return unit(new fast_.Graph_.Unit(), j); }
  public fast_.Graph_.Unit unit(fast_.Graph_.Unit obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int unitLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createGraph(FlatBufferBuilder builder,
      int unitOffset) {
    builder.startObject(1);
    Graph.addUnit(builder, unitOffset);
    return Graph.endGraph(builder);
  }

  public static void startGraph(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUnit(FlatBufferBuilder builder, int unitOffset) { builder.addOffset(0, unitOffset, 0); }
  public static int createUnitVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUnitVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGraph(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

