// automatically generated by the FlatBuffers compiler, do not modify

package fast_;

public final class Python3Kind {
  private Python3Kind() { }
  public static final int single_input = 0;
  public static final int file_input = 1;
  public static final int eval_input = 2;
  public static final int decorator = 3;
  public static final int decorators = 4;
  public static final int decorated = 5;
  public static final int async_funcdef = 6;
  public static final int funcdef = 7;
  public static final int parameters = 8;
  public static final int typedargslist = 9;
  public static final int tfpdef = 10;
  public static final int varargslist = 11;
  public static final int vfpdef = 12;
  public static final int stmt = 13;
  public static final int simple_stmt = 14;
  public static final int small_stmt = 15;
  public static final int expr_stmt = 16;
  public static final int annassign = 17;
  public static final int testlist_star_expr = 18;
  public static final int augassign = 19;
  public static final int del_stmt = 20;
  public static final int pass_stmt = 21;
  public static final int flow_stmt = 22;
  public static final int break_stmt = 23;
  public static final int continue_stmt = 24;
  public static final int return_stmt = 25;
  public static final int yield_stmt = 26;
  public static final int raise_stmt = 27;
  public static final int import_stmt = 28;
  public static final int import_name = 29;
  public static final int import_from = 30;
  public static final int import_as_name = 31;
  public static final int dotted_as_name = 32;
  public static final int import_as_names = 33;
  public static final int dotted_as_names = 34;
  public static final int dotted_name = 35;
  public static final int global_stmt = 36;
  public static final int nonlocal_stmt = 37;
  public static final int assert_stmt = 38;
  public static final int compound_stmt = 39;
  public static final int async_stmt = 40;
  public static final int if_stmt = 41;
  public static final int while_stmt = 42;
  public static final int for_stmt = 43;
  public static final int try_stmt = 44;
  public static final int with_stmt = 45;
  public static final int with_item = 46;
  public static final int except_clause = 47;
  public static final int suite = 48;
  public static final int test = 49;
  public static final int test_nocond = 50;
  public static final int lambdef = 51;
  public static final int lambdef_nocond = 52;
  public static final int or_test = 53;
  public static final int and_test = 54;
  public static final int not_test = 55;
  public static final int comparison = 56;
  public static final int comp_op = 57;
  public static final int star_expr = 58;
  public static final int expr = 59;
  public static final int xor_expr = 60;
  public static final int and_expr = 61;
  public static final int shift_expr = 62;
  public static final int arith_expr = 63;
  public static final int term = 64;
  public static final int factor = 65;
  public static final int power = 66;
  public static final int atom_expr = 67;
  public static final int atom = 68;
  public static final int testlist_comp = 69;
  public static final int trailer = 70;
  public static final int subscriptlist = 71;
  public static final int subscript = 72;
  public static final int sliceop = 73;
  public static final int exprlist = 74;
  public static final int testlist = 75;
  public static final int dictorsetmaker = 76;
  public static final int classdef = 77;
  public static final int arglist = 78;
  public static final int argument = 79;
  public static final int comp_iter = 80;
  public static final int comp_for = 81;
  public static final int comp_if = 82;
  public static final int encoding_decl = 83;
  public static final int yield_expr = 84;
  public static final int yield_arg = 85;

  public static final String[] names = { "single_input", "file_input", "eval_input", "decorator", "decorators", "decorated", "async_funcdef", "funcdef", "parameters", "typedargslist", "tfpdef", "varargslist", "vfpdef", "stmt", "simple_stmt", "small_stmt", "expr_stmt", "annassign", "testlist_star_expr", "augassign", "del_stmt", "pass_stmt", "flow_stmt", "break_stmt", "continue_stmt", "return_stmt", "yield_stmt", "raise_stmt", "import_stmt", "import_name", "import_from", "import_as_name", "dotted_as_name", "import_as_names", "dotted_as_names", "dotted_name", "global_stmt", "nonlocal_stmt", "assert_stmt", "compound_stmt", "async_stmt", "if_stmt", "while_stmt", "for_stmt", "try_stmt", "with_stmt", "with_item", "except_clause", "suite", "test", "test_nocond", "lambdef", "lambdef_nocond", "or_test", "and_test", "not_test", "comparison", "comp_op", "star_expr", "expr", "xor_expr", "and_expr", "shift_expr", "arith_expr", "term", "factor", "power", "atom_expr", "atom", "testlist_comp", "trailer", "subscriptlist", "subscript", "sliceop", "exprlist", "testlist", "dictorsetmaker", "classdef", "arglist", "argument", "comp_iter", "comp_for", "comp_if", "encoding_decl", "yield_expr", "yield_arg", };

  public static String name(int e) { return names[e]; }
}

