// automatically generated by the FlatBuffers compiler, do not modify

package fast_;

public final class SolidityKind {
  private SolidityKind() { }
  public static final int sourceunit = 0;
  public static final int pragmadirective = 1;
  public static final int pragmaname = 2;
  public static final int pragmavalue = 3;
  public static final int version = 4;
  public static final int versionoperator = 5;
  public static final int versionconstraint = 6;
  public static final int importdeclaration = 7;
  public static final int importdirective = 8;
  public static final int contractdefinition = 9;
  public static final int inheritancespecifier = 10;
  public static final int contractpart = 11;
  public static final int statevariabledeclaration = 12;
  public static final int usingfordeclaration = 13;
  public static final int structdefinition = 14;
  public static final int modifierdefinition = 15;
  public static final int modifierinvocation = 16;
  public static final int functiondefinition = 17;
  public static final int returnparameters = 18;
  public static final int modifierlist = 19;
  public static final int eventdefinition = 20;
  public static final int enumvalue = 21;
  public static final int enumdefinition = 22;
  public static final int indexedparameterlist = 23;
  public static final int indexedparameter = 24;
  public static final int parameterlist = 25;
  public static final int parameter = 26;
  public static final int typenamelist = 27;
  public static final int unnamedparameter = 28;
  public static final int variabledeclaration = 29;
  public static final int typename = 30;
  public static final int userdefinedtypename = 31;
  public static final int mapping = 32;
  public static final int functiontypename = 33;
  public static final int storagelocation = 34;
  public static final int statemutability = 35;
  public static final int block = 36;
  public static final int statement = 37;
  public static final int expressionstatement = 38;
  public static final int ifstatement = 39;
  public static final int whilestatement = 40;
  public static final int simplestatement = 41;
  public static final int forstatement = 42;
  public static final int inlineassemblystatement = 43;
  public static final int dowhilestatement = 44;
  public static final int continuestatement = 45;
  public static final int breakstatement = 46;
  public static final int returnstatement = 47;
  public static final int throwstatement = 48;
  public static final int variabledeclarationstatement = 49;
  public static final int identifierlist = 50;
  public static final int elementarytypename = 51;
  public static final int expression = 52;
  public static final int primaryexpression = 53;
  public static final int expressionlist = 54;
  public static final int namevaluelist = 55;
  public static final int namevalue = 56;
  public static final int functioncallarguments = 57;
  public static final int assemblyblock = 58;
  public static final int assemblyitem = 59;
  public static final int assemblyexpression = 60;
  public static final int assemblycall = 61;
  public static final int assemblylocaldefinition = 62;
  public static final int assemblyassignment = 63;
  public static final int assemblyidentifierorlist = 64;
  public static final int assemblyidentifierlist = 65;
  public static final int assemblyrightassignment = 66;
  public static final int labeldefinition = 67;
  public static final int assemblyswitch = 68;
  public static final int assemblycase = 69;
  public static final int assemblyfunctiondefinition = 70;
  public static final int assemblyfor = 71;
  public static final int assemblyliteral = 72;
  public static final int subassembly = 73;
  public static final int datasize = 74;
  public static final int linkersymbol = 75;
  public static final int tupleexpression = 76;
  public static final int elementarytypenameexpression = 77;
  public static final int numberliteral = 78;
  public static final int identifier = 79;

  public static final String[] names = { "sourceunit", "pragmadirective", "pragmaname", "pragmavalue", "version", "versionoperator", "versionconstraint", "importdeclaration", "importdirective", "contractdefinition", "inheritancespecifier", "contractpart", "statevariabledeclaration", "usingfordeclaration", "structdefinition", "modifierdefinition", "modifierinvocation", "functiondefinition", "returnparameters", "modifierlist", "eventdefinition", "enumvalue", "enumdefinition", "indexedparameterlist", "indexedparameter", "parameterlist", "parameter", "typenamelist", "unnamedparameter", "variabledeclaration", "typename", "userdefinedtypename", "mapping", "functiontypename", "storagelocation", "statemutability", "block", "statement", "expressionstatement", "ifstatement", "whilestatement", "simplestatement", "forstatement", "inlineassemblystatement", "dowhilestatement", "continuestatement", "breakstatement", "returnstatement", "throwstatement", "variabledeclarationstatement", "identifierlist", "elementarytypename", "expression", "primaryexpression", "expressionlist", "namevaluelist", "namevalue", "functioncallarguments", "assemblyblock", "assemblyitem", "assemblyexpression", "assemblycall", "assemblylocaldefinition", "assemblyassignment", "assemblyidentifierorlist", "assemblyidentifierlist", "assemblyrightassignment", "labeldefinition", "assemblyswitch", "assemblycase", "assemblyfunctiondefinition", "assemblyfor", "assemblyliteral", "subassembly", "datasize", "linkersymbol", "tupleexpression", "elementarytypenameexpression", "numberliteral", "identifier", };

  public static String name(int e) { return names[e]; }
}

