// automatically generated by the FlatBuffers compiler, do not modify

package fast_.Data_;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous3 extends Table {
  public static Anonymous3 getRootAsAnonymous3(ByteBuffer _bb) { return getRootAsAnonymous3(_bb, new Anonymous3()); }
  public static Anonymous3 getRootAsAnonymous3(ByteBuffer _bb, Anonymous3 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fast_.Element element() { return element(new fast_.Element()); }
  public fast_.Element element(fast_.Element obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Log log() { return log(new fast_.Log()); }
  public fast_.Log log(fast_.Log obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Delta delta() { return delta(new fast_.Delta()); }
  public fast_.Delta delta(fast_.Delta obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Pairs pairs() { return pairs(new fast_.Pairs()); }
  public fast_.Pairs pairs(fast_.Pairs obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Slices slices() { return slices(new fast_.Slices()); }
  public fast_.Slices slices(fast_.Slices obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Bugs bugs() { return bugs(new fast_.Bugs()); }
  public fast_.Bugs bugs(fast_.Bugs obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public fast_.Graph graph() { return graph(new fast_.Graph()); }
  public fast_.Graph graph(fast_.Graph obj) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createAnonymous3(FlatBufferBuilder builder,
      int elementOffset,
      int logOffset,
      int deltaOffset,
      int pairsOffset,
      int slicesOffset,
      int bugsOffset,
      int graphOffset) {
    builder.startObject(7);
    Anonymous3.addGraph(builder, graphOffset);
    Anonymous3.addBugs(builder, bugsOffset);
    Anonymous3.addSlices(builder, slicesOffset);
    Anonymous3.addPairs(builder, pairsOffset);
    Anonymous3.addDelta(builder, deltaOffset);
    Anonymous3.addLog(builder, logOffset);
    Anonymous3.addElement(builder, elementOffset);
    return Anonymous3.endAnonymous3(builder);
  }

  public static void startAnonymous3(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addElement(FlatBufferBuilder builder, int elementOffset) { builder.addOffset(0, elementOffset, 0); }
  public static void addLog(FlatBufferBuilder builder, int logOffset) { builder.addOffset(1, logOffset, 0); }
  public static void addDelta(FlatBufferBuilder builder, int deltaOffset) { builder.addOffset(2, deltaOffset, 0); }
  public static void addPairs(FlatBufferBuilder builder, int pairsOffset) { builder.addOffset(3, pairsOffset, 0); }
  public static void addSlices(FlatBufferBuilder builder, int slicesOffset) { builder.addOffset(4, slicesOffset, 0); }
  public static void addBugs(FlatBufferBuilder builder, int bugsOffset) { builder.addOffset(5, bugsOffset, 0); }
  public static void addGraph(FlatBufferBuilder builder, int graphOffset) { builder.addOffset(6, graphOffset, 0); }
  public static int endAnonymous3(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

